# Generated by Django 3.2.12 on 2022-05-26 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='posting',
            new_name='post',
        ),
    ]
