# Generated by Django 3.2.12 on 2022-05-31 03:59

from django.db import migrations, models
import sqlalchemy.sql.expression


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20220526_0703'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=sqlalchemy.sql.expression.true, upload_to='images/'),
        ),
    ]
