# Generated by Django 3.2.12 on 2022-05-31 15:37

from django.db import migrations, models
import sqlalchemy.sql.expression


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=sqlalchemy.sql.expression.true, upload_to='images/'),
        ),
    ]
